-- View club competition results (placings, arrow totals, scores).
-- ------------------------------------------------------------------------------------------------
-- Description...
-- Technical description...

-- View yearly club championship results and identify winners.
-- ------------------------------------------------------------------------------------------------
-- Description...
-- Technical description...
