-- View club competition results (placings, arrow totals, scores).
-- ------------------------------------------------------------------------------------------------
-- Description...
-- Technical description...
select
from competition c
join roundscore rs on c.id = rs.competitionid
-- View yearly club championship results and identify winners.
-- ------------------------------------------------------------------------------------------------
-- Description...
-- Technical description...
