import random
from datetime import date, timedelta

# Sample data pools for realistic generation
first_names_male = [
    "James", "John", "Robert", "Michael", "William", "David", "Richard", "Joseph",
    "Thomas", "Charles", "Christopher", "Daniel", "Matthew", "Anthony", "Mark",
    "Donald", "Steven", "Paul", "Andrew", "Joshua", "Kenneth", "Kevin", "Brian",
    "George", "Edward", "Ronald", "Timothy", "Jason", "Jeffrey", "Ryan", "Jacob",
    "Gary", "Nicholas", "Eric", "Jonathan", "Stephen", "Larry", "Justin", "Scott",
    "Brandon", "Frank", "Benjamin", "Gregory", "Samuel", "Raymond", "Patrick",
    "Alexander", "Jack", "Dennis", "Jerry", "Tyler", "Aaron", "Henry", "Adam",
    "Douglas", "Nathan", "Peter", "Zachary", "Kyle", "Walter", "Harold", "Ethan",
    "Carl", "Keith", "Roger", "Gerald", "Christian", "Terry", "Sean", "Arthur"
]

first_names_female = [
    "Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan",
    "Jessica", "Sarah", "Karen", "Lisa", "Nancy", "Betty", "Sandra", "Margaret",
    "Ashley", "Kimberly", "Emily", "Donna", "Michelle", "Carol", "Amanda", "Melissa",
    "Deborah", "Stephanie", "Dorothy", "Rebecca", "Sharon", "Laura", "Cynthia",
    "Amy", "Kathleen", "Angela", "Shirley", "Brenda", "Emma", "Anna", "Pamela",
    "Nicole", "Samantha", "Katherine", "Christine", "Helen", "Debra", "Rachel",
    "Carolyn", "Janet", "Maria", "Catherine", "Heather", "Diane", "Olivia",
    "Julie", "Joyce", "Victoria", "Ruth", "Virginia", "Lauren", "Kelly", "Christina",
    "Joan", "Evelyn", "Judith", "Andrea", "Hannah", "Megan", "Cheryl", "Jacqueline"
]

last_names = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
    "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson",
    "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson",
    "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker",
    "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores",
    "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell",
    "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz", "Parker",
    "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", "Morales", "Murphy",
    "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper", "Peterson", "Bailey",
    "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward", "Richardson", "Watson",
    "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes"
]

def random_date(start_year=1950, end_year=2010):
    """Generate a random date of birth between two years."""
    start = date(start_year, 1, 1)
    end = date(end_year, 12, 31)
    delta = (end - start).days
    return start + timedelta(days=random.randint(0, delta))

def escape_sql(value):
    """Escape single quotes in SQL strings."""
    return value.replace("'", "''")

# Generate 1000 INSERT statements
insert_statements = []
insert_statements.append("-- 1000 INSERT statements for the Archer table")
insert_statements.append("-- Generated by Python script")
insert_statements.append("")

for i in range(1000):
    # Randomly choose gender
    gender_choice = random.choice(["Male", "Female"])
    
    if gender_choice == "Male":
        first_name = random.choice(first_names_male)
    else:
        first_name = random.choice(first_names_female)
    
    last_name = random.choice(last_names)
    dob = random_date()
    
    # DefaultEquipmentID and ClubID - assume 1-20 equipment types and 1-50 clubs exist
    # Allow some NULLs to reflect optional foreign keys
    default_equipment_id = random.choice([random.randint(1, 20), "NULL"])
    club_id = random.choice([random.randint(1, 50), "NULL"])
    
    statement = (
        f"INSERT INTO Archer (firstName, lastName, Gender, DOB, DefaultEquipmentID, ClubID) "
        f"VALUES ('{escape_sql(first_name)}', '{escape_sql(last_name)}', "
        f"'{gender_choice}', '{dob.isoformat()}', {default_equipment_id}, {club_id});"
    )
    insert_statements.append(statement)

# Write everything to the output file
output_path = "archer_inserts.sql"
with open(output_path, "w") as f:
    f.write("\n".join(insert_statements))

print(f"Successfully generated 1000 INSERT statements at {output_path}")
print(f"\nFirst 3 sample statements:")
for stmt in insert_statements[3:6]:
    print(stmt)